spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop_night  
    username: phoneshop_night
    password: 123a
  jpa:
    properties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
            ddl-auto: update